# Generated by Django 2.2.2 on 2019-06-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('background_color', models.CharField(max_length=20, null=True)),
                ('opening_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
